### PR TITLE
Pin bandit version

### PR DESCRIPTION
**Pull request by jm-wk**
We pin the version of Bandit SAST tool to make the CI tests more predictable. If we used the latest version available without pinning it, the CI tests could start failing on new Bandit version without any changes in our codebase.

We pin the Bandit version by adding version requirement to tox.ini.

### CODE REVIEW

**Review by rohanpm — DISMISSED** [review]

**Comment by rohanpm** [comment]
It seems there are conflicts.  Can you please resolve them?

**Comment by rohanpm** [comment]
CI is broken by https://github.com/junaruga/rpm-py-installer/issues/276, we're going to need a workaround like https://github.com/release-engineering/pushsource/pull/332 to unbreak it.

**Comment by jm-wk** [comment]
Thanks for the comments. 

I have created a CI workaround PR here: https://github.com/release-engineering/pubtools-ami/pull/105

**Comment by rohanpm** [comment]
Could you please rebase this now to get a successful CI run?

**Review by rohanpm — APPROVED** [review]

**Pull request merged**
